import { FileTreeNode } from "virtual:file-tree";

// noinspection JSUnusedGlobalSymbols
export const fileTree: FileTreeNode[] = [
  {
    name: "src",
    path: "",
    isDirectory: true,
    blocks: 8,
    permissions: [6, 6, 4],
    children: [
      {
        name: "main",
        path: "src",
        isDirectory: true,
        blocks: 8,
        permissions: [6, 6, 4],
        children: [
          {
            name: "foo",
            path: "src/main",
            isDirectory: true,
            blocks: 8,
            permissions: [6, 6, 4],
            children: [
              {
                name: "bar",
                path: "src/main/foo",
                isDirectory: true,
                blocks: 8,
                permissions: [6, 6, 4],
                children: [],
                lastModifiedTime: new Date(2000, 0),
                size: 0,
                owner: "nathanwise",
                group: "nathanwise",
              },
              {
                name: "daz",
                path: "src/main/foo",
                isDirectory: false,
                blocks: 12,
                lastModifiedTime: new Date(2000, 0),
                size: 0,
                permissions: [6, 6, 4],
                owner: "nathanwise",
                group: "nathanwise",
              },
              {
                name: "bazzing.gaz",
                path: "src/main/foo",
                isDirectory: false,
                blocks: 23,
                lastModifiedTime: new Date(2000, 0),
                size: 0,
                permissions: [6, 6, 4],
                owner: "nathanwise",
                group: "nathanwise",
              },
            ],
            lastModifiedTime: new Date(2000, 0),
            size: 0,
            owner: "nathanwise",
            group: "nathanwise",
          },
          {
            name: ".testing",
            path: "src/main",
            isDirectory: false,
            blocks: 19,
            lastModifiedTime: new Date(2000, 0),
            size: 0,
            permissions: [6, 6, 4],
            owner: "nathanwise",
            group: "nathanwise",
          },
          {
            name: ".empty",
            path: "src/main",
            isDirectory: true,
            blocks: 8,
            children: [],
            lastModifiedTime: new Date(2000, 0),
            size: 0,
            permissions: [6, 6, 4],
            owner: "nathanwise",
            group: "nathanwise",
          },
          {
            name: ".full",
            path: "src/main",
            isDirectory: true,
            blocks: 8,
            children: [
              {
                name: "someEmptyDir",
                path: "src/main/.full",
                isDirectory: true,
                children: [],
                lastModifiedTime: new Date(2000, 0),
                size: 0,
                permissions: [6, 6, 4],
                owner: "nathanwise",
                group: "nathanwise",
                blocks: 0,
              },
              {
                name: "aFile",
                path: "src/main/.full",
                isDirectory: false,
                blocks: 12,
                lastModifiedTime: new Date(2000, 0),
                size: 0,
                permissions: [6, 6, 4],
                owner: "nathanwise",
                group: "nathanwise",
              },
            ],
            lastModifiedTime: new Date(2000, 0),
            size: 0,
            permissions: [6, 6, 4],
            owner: "nathanwise",
            group: "nathanwise",
          },
        ],
        lastModifiedTime: new Date(2000, 0),
        size: 0,
        owner: "nathanwise",
        group: "nathanwise",
      },
      {
        name: "index.ts",
        path: "src",
        isDirectory: false,
        blocks: 52,
        lastModifiedTime: new Date(2000, 0),
        size: 0,
        permissions: [6, 6, 4],
        owner: "nathanwise",
        group: "nathanwise",
      },
    ],
    lastModifiedTime: new Date(2000, 0),
    size: 0,
    owner: "nathanwise",
    group: "nathanwise",
  },
  {
    name: "test",
    path: "",
    isDirectory: true,
    blocks: 8,
    children: [],
    lastModifiedTime: new Date(2000, 0),
    size: 0,
    permissions: [6, 6, 4],
    owner: "nathanwise",
    group: "nathanwise",
  },
];
