// TODO: Tests for...
//  - Test in user input and readonly...
//    - Pressing Enter should run a command & prevent a newline in the frontend
//    - Pressing Shift Enter should NOT run a command & append a newline in the frontend
